<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net10.0</TargetFrameworks>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="Earth.docx" />
    <None Remove="Jupiter.docx" />
    <None Remove="Mars.docx" />
    <None Remove="Mercury.docx" />
    <None Remove="Neptune.docx" />
    <None Remove="Pluto.docx" />
    <None Remove="Saturn.docx" />
    <None Remove="solar-system.docx" />
    <None Remove="SolarOverview.docx" />
    <None Remove="Sun.docx" />
    <None Remove="Uranus.docx" />
    <None Remove="Venus.docx" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Earth.docx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Jupiter.docx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Mars.docx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Mercury.docx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Neptune.docx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Pluto.docx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Saturn.docx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="solar-system.docx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="SolarOverview.docx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Sun.docx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Uranus.docx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Venus.docx">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DocumentFormat.OpenXml" Version="3.5.1" />
  </ItemGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'net481' ">
    <Reference Include="WindowsBase" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\OpenXmlPowerTools.Core\OpenXmlPowerTools.Core.csproj" />
    <ProjectReference Include="..\..\OpenXmlPowerTools.DocumentAssembler\OpenXmlPowerTools.DocumentAssembler.csproj" />
    <ProjectReference Include="..\..\OpenXmlPowerTools.DocumentBuilder\OpenXmlPowerTools.DocumentBuilder.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="StyleCop.Analyzers" Version="1.1.118" />
  </ItemGroup>
</Project>